### ISSUE TITLE
Map 450012120 "MapRender加载失败，没有地图数据"

### ISSUE THREAD

**Issue by Dban1** [Kagamia/WzComparerR2#114]
Hi! I have searched for this issue on here but although steps have been taken to amend this problem for some maps, this still happens for this map with NO npc. I wonder what's causing the issue? 

This is the error log:

`[2019-08-07 00:31:41][Error][MapRender] Coroutine Error: System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
   at WzComparerR2.MapRender.ResourceLoader.Load[T](Wz_Node node, String assetName)
   at WzComparerR2.MapRender.ResourceLoader.Load[T](Wz_Node node)
   at WzComparerR2.MapRender.ResourceLoader.LoadFrame(Wz_Node node)
   at WzComparerR2.MapRender.ResourceLoader.InnerLoadAnimationData(Wz_Node node)
   at WzComparerR2.MapRender.ResourceLoader.LoadAnimationData(Wz_Node node)
   at WzComparerR2.MapRender.MapData.CreateSMAnimator(Wz_Node node, ResourceLoader resLoader)
   at WzComparerR2.MapRender.MapData.PreloadResource(ResourceLoader resLoader, LifeItem life)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass78_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass78_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass78_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass78_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass78_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.PreloadResource(ResourceLoader resLoader)
   at WzComparerR2.MapRender.FrmMapRender2.<LoadMap>d__66.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
   at WzComparerR2.MapRender.ResourceLoader.Load[T](Wz_Node node, String assetName)
   at WzComparerR2.MapRender.ResourceLoader.Load[T](Wz_Node node)
   at WzComparerR2.MapRender.ResourceLoader.LoadFrame(Wz_Node node)
   at WzComparerR2.MapRender.ResourceLoader.InnerLoadAnimationData(Wz_Node node)
   at WzComparerR2.MapRender.ResourceLoader.LoadAnimationData(Wz_Node node)
   at WzComparerR2.MapRender.MapData.CreateSMAnimator(Wz_Node node, ResourceLoader resLoader)
   at WzComparerR2.MapRender.MapData.PreloadResource(ResourceLoader resLoader, LifeItem life)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass78_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass78_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass78_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass78_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass78_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.PreloadResource(ResourceLoader resLoader)
   at WzComparerR2.MapRender.FrmMapRender2.<LoadMap>d__66.MoveNext()<---
`

**Comment by Kagamia** [comment]
![image](https://user-images.githubusercontent.com/10445904/62588021-d5350c80-b8f6-11e9-8abe-19232c69ec12.png)
Renders well for my CMST client.
Have you compiled the latest version?

**Comment by Dban1** [comment]
Hi, I think it works now. My wz files were corrupted apparently!
