### ISSUE TITLE
KMST 1.2.104 - Cannot Load Certain NPC Images

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#138]
KMST 1.2.104 released a few new NPCs with IDs starting with 257XXXX, but some of them cannot be loaded. For example, trying to load any of the new sprites for 2570100 gives a NullReferenceException.
![image](https://user-images.githubusercontent.com/34289651/87094286-a0b78800-c20c-11ea-8747-620ce4be2b13.png)

Error log:
````
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at WzComparerR2.Rendering.MonogameUtils.ToTexture(Bitmap bitmap, Texture2D texture, Point origin) in C:\Izzy\WzComparerR2-source\WzComparerR2-Code\WzComparerR2.Common\Rendering\MonogameUtils.cs:line 86
   at WzComparerR2.Rendering.WzLibExtension.ToTexture(Wz_Png png, Texture2D texture, Point origin) in C:\Izzy\WzComparerR2-source\WzComparerR2-Code\WzComparerR2.Common\Rendering\WzLibExtension.cs:line 64
   at WzComparerR2.Rendering.WzLibExtension.ToTexture(Wz_Png png, GraphicsDevice graphicsDevice) in C:\Izzy\WzComparerR2-source\WzComparerR2-Code\WzComparerR2.Common\Rendering\WzLibExtension.cs:line 43
   at WzComparerR2.PictureBoxEx.ShowImage(Wz_Png png) in C:\Izzy\WzComparerR2-source\WzComparerR2-Code\WzComparerR2\PictureBoxEx.cs:line 61
   at WzComparerR2.MainForm.advTree3_AfterNodeSelect(Object sender, AdvTreeNodeEventArgs e) in C:\Izzy\WzComparerR2-source\WzComparerR2-Code\WzComparerR2\MainForm.cs:line 1071
   at DevComponents.AdvTree.AdvTreeNodeEventHandler.Invoke(Object sender, AdvTreeNodeEventArgs e)
   at DevComponents.AdvTree.AdvTree.OnAfterNodeSelect(AdvTreeNodeEventArgs args)
   at DevComponents.AdvTree.AdvTree.SelectNode(Node node, eTreeAction action)
   at DevComponents.AdvTree.AdvTree.ٹ(Node ْ, MouseEventArgs ؾ, Point ٧)
   at DevComponents.AdvTree.AdvTree.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


````

**Comment by Kagamia** [comment]
Thanks for reporting, the latest commit fixed that. https://github.com/Kagamia/WzComparerR2/commit/0c720d27dbd3e1daaafc214691a3be38370cf83b

![image](https://user-images.githubusercontent.com/10445904/87111820-de63f180-c29c-11ea-8d8b-818a744a6585.png)

**Comment by PirateIzzy** [comment]
So I tried to save some of the new images, a couple of them save fine
![image](https://user-images.githubusercontent.com/34289651/87113907-4f73bc80-c23d-11ea-8b55-949a33907562.png)

but a few others become distorted when I save them:
![image](https://user-images.githubusercontent.com/34289651/87113930-5bf81500-c23d-11ea-993f-71ffb1f84dda.png)

**Comment by Kagamia** [comment]
All fixed in https://github.com/Kagamia/WzComparerR2/commit/fd64241240069fd3d81784109d2970fabdc78480

**Comment by PirateIzzy** [comment]
![image](https://user-images.githubusercontent.com/34289651/87154243-e44ed800-c286-11ea-96e0-76cc5c13c5c4.png)
![image](https://user-images.githubusercontent.com/34289651/87154251-e87af580-c286-11ea-8948-bff92ad5caa3.png)
All fixed, thanks.
