### ISSUE TITLE
Crash upon skeleton animation 

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#26]
Hey there,

I've tried saving a few skeleton animations through Map.img and it works. However, when I try to save **Map.img\Back\Effect3.img\BossLucid\Lucid.atlas**, it gives me an error.

"System.OutOfMemoryException."

`System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown
   at WzComparerR2.PictureBoxEx.SaveAsGif(AnimationItem aniItem, String fileName, ImageHandlerConfig config) in C:\Users\Desktop\WzComparerR2 Localization\GMS\Stable\WzComparerR2\WzComparerR2\PictureBoxEx.cs:line 158
   at WzComparerR2.MainForm.buttonItemSaveImage_Click(Object sender, EventArgs e) in C:\Users\Desktop\WzComparerR2 Localization\GMS\Stable\WzComparerR2\WzComparerR2\MainForm.cs:line 438
   at DevComponents.DotNetBar.BaseItem.RaiseClick(eEventSource source)
   at DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.PopupItem.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.ButtonItem.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.ItemContainer.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.ItemControl.OnMouseUp(MouseEventArgs e)
   at DevComponents.DotNetBar.RibbonBar.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at DevComponents.DotNetBar.ItemControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

Update 2:

I tried saving Kinesis character at **UI.img\Login.img\RaceSelect_new\Back0\18\Kinesis.atlas**. It kind of works, but I get the following error:

`System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Value of -252 is not valid for red. Red must be greater than or equal to 0 and less than or equal to 255.
   at System.Drawing.Color.CheckByte(Int32 value, String name)
   at System.Drawing.Color.FromArgb(Int32 alpha, Int32 red, Int32 green, Int32 blue)
   at System.Drawing.Color.FromArgb(Int32 red, Int32 green, Int32 blue)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.Palletize(Int32 colorCount)
   at ImageManipulation.OctreeQuantizer.GetPalette(ColorPalette original)
   at ImageManipulation.Quantizer.Quantize(Image source)
   at WzComparerR2.Common.BuildInGifEncoder.AppendFrame(Bitmap image, Int32 delay)
   at WzComparerR2.Common.BuildInGifEncoder.AppendFrame(IntPtr pBuffer, Int32 delay)
   at WzComparerR2.PictureBoxEx.<>c__DisplayClass28_3.<SaveAsGif>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of Internal Exceptional Stackway ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at WzComparerR2.PictureBoxEx.<>c__DisplayClass28_0.<SaveAsGif>b__0(Int32 curTime)
   at WzComparerR2.PictureBoxEx.SaveAsGif(AnimationItem aniItem, String fileName, ImageHandlerConfig config)
   at WzComparerR2.MainForm.buttonItemSaveImage_Click(Object sender, EventArgs e)
   at DevComponents.DotNetBar.BaseItem.RaiseClick(eEventSource source)
   at DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.PopupItem.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.ButtonItem.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.ItemContainer.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.ItemControl.OnMouseUp(MouseEventArgs e)
   at DevComponents.DotNetBar.RibbonBar.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at DevComponents.DotNetBar.ItemControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Internal exception #0) System.ArgumentException: Value of -252 is not valid for red. Red must be greater than or equal to 0 and less than or equal to 255.
   at System.Drawing.Color.CheckByte(Int32 value, String name)
   at System.Drawing.Color.FromArgb(Int32 alpha, Int32 red, Int32 green, Int32 blue)
   at System.Drawing.Color.FromArgb(Int32 red, Int32 green, Int32 blue)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.Palletize(Int32 colorCount)
   at ImageManipulation.OctreeQuantizer.GetPalette(ColorPalette original)
   at ImageManipulation.Quantizer.Quantize(Image source)
   at WzComparerR2.Common.BuildInGifEncoder.AppendFrame(Bitmap image, Int32 delay)
   at WzComparerR2.Common.BuildInGifEncoder.AppendFrame(IntPtr pBuffer, Int32 delay)
   at WzComparerR2.PictureBoxEx.<>c__DisplayClass28_3.<SaveAsGif>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---`

Saving the image at **UI.img\Login.img\RaceSelect_new\Back0\19\skeleton.atlas** (Cadena job) works fine without errors
See: (https://media.giphy.com/media/3o8dFzNF1dvRwPKukM/giphy.gif)

**Comment by Kagamia** [comment]
1> try compiling wcR2 with `anyCPU/x64` options, maybe there're some memory leaks.
2> Unexpected bug :( , try with `Index GIF Encoder`.

**Comment by Sunaries** [comment]
@Kagamia This happened with AnyCPU. I tried x64 and it does the same. Still gives the `System.OutOfMemoryException` error. Index GIF Encoder crashes with it as well.

**Comment by Kagamia** [comment]
`Map.img\Back\Effect3.img\BossLucid\Lucid.atlas` 
The full size of this animaton is about 10k*10k pixels, so............ just give up.

**Comment by Sunaries** [comment]
@Kagamia 😢

**Comment by Sunaries** [comment]
[!](https://cdn.discordapp.com/attachments/88992151643369472/340069396728905728/22222.png)

Blocky-ness.

**Comment by Kagamia** [comment]
@Sunaries 
It's the first time that skeleton use `BlendMode.Multiply`, which I have not implemented in `spine-monogame`.

Fixed, but it won't support dump GIF with transparent background at all.
![back0 20 skeleton atlas animation](https://user-images.githubusercontent.com/10445904/28703006-90566eb0-7393-11e7-8d49-c3806755d9aa.gif)

**Comment by KENNYSOFT** [comment]
Wow!
