### ISSUE TITLE
KMST 1.2.173: Certain Skill Tooltips give an error

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#260]
A few new skills were added in KMST 1.2.173 as part of the anniversary event give errors when rendering.

![image](https://github.com/Kagamia/WzComparerR2/assets/34289651/3438f18a-4ec3-4ff8-9bc8-e5ef044e04ba)
It applies to skill IDs 80003671, 80003672, and 80003677

Stack trace:
```
************** Exception Text **************
System.InvalidOperationException: Stack empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Pop()
   at WzComparerR2.Calculator.Suffix(List`1 tokens)
   at WzComparerR2.Calculator.Parse(String mathExpression, Decimal[] args)
   at WzComparerR2.CharaSim.SummaryParser.GetSkillSummary(String H, Int32 Level, Dictionary`2 CommonProps, SummaryParams param, SkillSummaryOptions options)
   at WzComparerR2.CharaSim.SummaryParser.GetSkillSummary(Skill skill, Int32 level, StringResult sr, SummaryParams param, SkillSummaryOptions options)
   at WzComparerR2.CharaSimControl.SkillTooltipRender2.RenderSkill(CanvasRegion region, Int32& picH, List`1& splitterH)
   at WzComparerR2.CharaSimControl.SkillTooltipRender2.Render()
   at WzComparerR2.CharaSimControl.AfrmTooltip.PreRender()
   at WzComparerR2.CharaSimControl.AfrmTooltip.Refresh()
   at WzComparerR2.MainForm.quickView(Node node)
   at WzComparerR2.MainForm.advTree2_AfterNodeSelect_2(Object sender, AdvTreeNodeEventArgs e)
   at DevComponents.AdvTree.AdvTreeNodeEventHandler.Invoke(Object sender, AdvTreeNodeEventArgs e)
   at DevComponents.AdvTree.AdvTree.OnAfterNodeSelect(AdvTreeNodeEventArgs args)
   at DevComponents.AdvTree.AdvTree.SelectNode(Node node, eTreeAction action)
   at DevComponents.AdvTree.AdvTree.ٹ(Node ْ, MouseEventArgs ؾ, Point ٧)
   at DevComponents.AdvTree.AdvTree.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Kagamia** [comment]
Any details? Could you help post a screenshot for the skill common properties?

**Comment by PirateIzzy** [comment]
This is from 80003671:
![image](https://github.com/Kagamia/WzComparerR2/assets/34289651/b0b2440b-b79f-424b-a067-1b8e56fd5743)

80003672:
![image](https://github.com/Kagamia/WzComparerR2/assets/34289651/e18b9daf-0aec-4968-ba75-ff659dda27d7)

80003677:
![image](https://github.com/Kagamia/WzComparerR2/assets/34289651/6954a8a5-8932-4a44-93dc-02a730ea8db3)

For comparison this is 80003670, which renders fine:
![image](https://github.com/Kagamia/WzComparerR2/assets/34289651/7a572bf1-025e-41f9-85a7-ab01998f0083)

I think the reason is because it has an extra `)` at the end, i.e. `10*x-5*d(x/2))` instead of `10*x-5*d(x/2)`

**Comment by Kagamia** [comment]
So it is still due to the wrong math expression.

 da*n Ne*on

**Comment by HikariCalyx** [comment]
I created a function named `ExcessiveBracketFilter` as a workaround for this issue, as shown in this commit:
https://github.com/HikariCalyx/WzComparerR2-JMS/commit/a3989c74d02f2346bb9e6546f4ddc64bf59144cb

![image](https://github.com/Kagamia/WzComparerR2/assets/29157608/035fb902-8195-4b57-8ecb-e7d0705bc547)

**Comment by Kagamia** [comment]
I believe there're only countable cases in wz, so I decided to workaround for the 3 cases.

Also add support for more special cases and functions even they're not appeared in skill desc.

```
15200.img, 152000009, w, min(x,10)-min(x,9)    // function min()
800004.img, 80000419, madX, 3*X    // upper case X
```
