### ISSUE TITLE
Spine Issue: Certain Angler Company Maps Don't Render

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#270]
The new maps for the Angler Company Epic Dungeon don't render map assets, aside from particles. Here is Map ID 993254100 for example:
![image](https://github.com/user-attachments/assets/52a21305-b5f9-447e-98ab-b300ac15f192)

![image](https://github.com/user-attachments/assets/2173d5c3-1601-46ce-98c7-1b25d9d0b207)

Not sure if it's the same as #266 , but there is no SystemAggregateException this time.

**Comment by Kagamia** [comment]
`RAWDATA` format breaking change.

**Comment by Kagamia** [comment]
Fixed. 

![image](https://github.com/user-attachments/assets/4b67a62d-7a62-44d7-b6dc-94eae3d7a568)

**Comment by HikariCalyx** [comment]
Map 993250000 still cannot be rendered.
```
[8-9-2024 08:20:31][Error][MapRender] Coroutine Error: System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WzComparerR2.MapRender.MapData.PreloadResource(ResourceLoader resLoader, PortalItem portal)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass92_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass92_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass92_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.PreloadResource(ResourceLoader resLoader)
   at WzComparerR2.MapRender.FrmMapRender2.LoadMap()
   --- End of inner exception stack trace ---
[8-9-2024 08:20:32][Error][MapRender] Coroutine Error: System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WzComparerR2.MapRender.MapData.PreloadResource(ResourceLoader resLoader, PortalItem portal)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass92_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass92_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass92_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.PreloadResource(ResourceLoader resLoader)
   at WzComparerR2.MapRender.FrmMapRender2.LoadMap()
   --- End of inner exception stack trace ---
[8-9-2024 08:20:38][Error][MapRender] Coroutine Error: System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WzComparerR2.MapRender.MapData.PreloadResource(ResourceLoader resLoader, PortalItem portal)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass92_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass92_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass92_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.PreloadResource(ResourceLoader resLoader)
   at WzComparerR2.MapRender.FrmMapRender2.LoadMap()
   --- End of inner exception stack trace ---
```
