### ISSUE TITLE
GMS v255 特定地图无法正常渲染

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#294]
ID: 867171000

```
[Error][MapRender] Coroutine Error: System.AggregateException: One or more errors occurred. (HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: 参数错误。
)
 ---> SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: 参数错误。

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at SharpDX.Direct3D11.Texture2D..ctor(Device device, Texture2DDescription description)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   at Microsoft.Xna.Framework.Graphics.Texture.GetTexture()
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformSetData[T](Int32 level, Int32 arraySlice, Rectangle rect, T[] data, Int32 startIndex, Int32 elementCount)
   at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T](Int32 level, Int32 arraySlice, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount)
   at WzComparerR2.Rendering.WzLibExtension.ToTexture(Wz_Png png, Texture2D texture, Point origin)
   at WzComparerR2.Rendering.WzLibExtension.ToTexture(Wz_Png png, GraphicsDevice graphicsDevice)
   at WzComparerR2.MapRender.ResourceLoader.InnerLoad(Wz_Node node, Type assetType)
   at WzComparerR2.MapRender.ResourceLoader.Load[T](Wz_Node node, String assetName)
   at WzComparerR2.MapRender.ResourceLoader.Load[T](Wz_Node node)
   at WzComparerR2.MapRender.ResourceLoader.LoadFrame(Wz_Node node)
   at WzComparerR2.MapRender.ResourceLoader.InnerLoadAnimationData(Wz_Node node)
   at WzComparerR2.MapRender.ResourceLoader.LoadAnimationData(Wz_Node node)
   at WzComparerR2.MapRender.ResourceLoader.LoadAnimationData(String assetName)
   at WzComparerR2.MapRender.MapData.PreloadResource(ResourceLoader resLoader, BackItem back)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass84_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.<>c__DisplayClass84_0.<PreloadResource>b__0(SceneNode node)
   at WzComparerR2.MapRender.MapData.PreloadResource(ResourceLoader resLoader)
   at WzComparerR2.MapRender.FrmMapRender2.LoadMap()
   --- End of inner exception stack trace ---
```
![image](https://github.com/user-attachments/assets/b3679b46-3716-47e0-933c-6eb9f45afa18)

**Comment by PirateIzzy** [comment]
Just an addendum, this is related to issue #266 .

**Comment by Kagamia** [comment]
Resolved in 266. Close issue.
