### ISSUE TITLE
System.ArgumentOutOfRangeException: Non-negative number required

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#36]
When comparing the new Private Test Server client of GMS with the public server client, I get the following error after it compares to Map.wz, making the comparer process incomplete.

```
The comparison was aborted. System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
 at System.IO.FileStream.set_Position(Int64 value)
 at WzComparerR2.WzLib.Wz_Image_GetCheckSum() in C:\Users\Desktop\WzComparerR2 Localization\GMS\Stable\WzComparerR2\WzComparerR2.WzLib\Wz_Image.cs:line 110
 at WzComparerR2.WzLib.Wz_Image_TryExtract(Exception&e) in C:\Users\Desktop\WzComparerR2 Localization\GMS\Stable\WzComparerR2\WzComparerR2.WzLib\Wz_Image.cs:line 57
 at WzComparerR2.Comparer.EasyComparer.CompareImg(Wz_Image imgNew, Wz_Image imgOld, String imgName, String anchorName, String menuAnchorName, String outputDir, StreamWriter sw) in C:\Users\Desktop\WzComparerR2 Localization\GMS\Stable\WzComparerR2\WzCompareR2\Comparer\EasyComparer.cs:line 406
 at WzComparerR2.Comparer.EasyComparer.OutputFile(List`1fileNew, List`1fileOld, Wz_Type type, List`1 diffLst, String outputDir, StreamWriter index) in C:\Users\Desktop\WzComparerR2 Localization\GMS\Stable\WzComparerR2\Comparer\EasyComparer.cs:line 329...
```

**Comment by Kagamia** [comment]
The wz file is broken.  wc never support a non-official client.

**Comment by Sunaries** [comment]
@Kagamia It is official client. It is GMST (tespia for GMS)

**Comment by Kagamia** [comment]
emmmm, Do you know which `wz_image` can not load, and print out detail informations about it?
Or, open the Map.wz stand alone, and test all images one by one. 😃

**Comment by KENNYSOFT** [comment]
![image](https://user-images.githubusercontent.com/6624567/29156035-9ea3a31a-7dda-11e7-9fa8-d07e84a18338.png)

As @Sunaries said, Map.wz is over 2147483647 Bytes. So https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.WzLib/Wz_Image.cs 's `Size` and `Offset` should be changed to `long`.

**Comment by Sunaries** [comment]
While I did change some `int` to `long`, I get build errors. @Kagamia We'll await your reply since you know the module.

**Comment by Kagamia** [comment]
Finally this day comes 😆 
I wonder how the patcher changed after this.

**Comment by Kagamia** [comment]
@Sunaries  try this commit : https://github.com/Kagamia/WzComparerR2/commit/5ecb5f308a1485f9a3d10dcd3f4b0b3d00eee6c7 , Of course I'm not sure whether it works. 😃

**Comment by Sunaries** [comment]
@Kagamia It worked. It successfully finished compare.
