### ISSUE TITLE
Error when rendering Skeleton Image

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#84]
New KMST v1070 update released today. 

```
System.AggregateException: One or more errors have occurred. ---> System.ArgumentException: Value of -231 is not valid for red. red must be greater than or equal to 0 and less than or equal to 255
   at System.Drawing.Color.CheckByte(Int32 value, String name)
   at System.Drawing.Color.FromArgb(Int32 alpha, Int32 red, Int32 green, Int32 blue)
   at System.Drawing.Color.FromArgb(Int32 red, Int32 green, Int32 blue)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.Palletize(Int32 colorCount)
   at ImageManipulation.OctreeQuantizer.GetPalette(ColorPalette original)
   at ImageManipulation.Quantizer.Quantize(Image source)
   at WzComparerR2.Common.BuildInGifEncoder.AppendFrame(Bitmap image, Int32 delay)
   at WzComparerR2.Common.BuildInGifEncoder.AppendFrame(IntPtr pBuffer, Int32 delay)
   at WzComparerR2.PictureBoxEx.<>c__DisplayClass30_4.<SaveAsGif>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of internal exception stack path ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at WzComparerR2.PictureBoxEx.<>c__DisplayClass30_0.<SaveAsGif>b__0(Int32 curTime)
   at WzComparerR2.PictureBoxEx.SaveAsGif(AnimationItem aniItem, String fileName, ImageHandlerConfig config)
   at WzComparerR2.MainForm.buttonItemSaveImage_Click(Object sender, EventArgs e)
   at DevComponents.DotNetBar.BaseItem.RaiseClick(eEventSource source)
   at DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.PopupItem.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.ButtonItem.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.ItemContainer.InternalMouseUp(MouseEventArgs objArg)
   at DevComponents.DotNetBar.ItemControl.OnMouseUp(MouseEventArgs e)
   at DevComponents.DotNetBar.RibbonBar.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at DevComponents.DotNetBar.ItemControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Internal exception #0) System.ArgumentException: Value of -231 is not valid for red. red must be greater than or equal to 0 and less than or equal to 255
   at System.Drawing.Color.CheckByte(Int32 value, String name)
   at System.Drawing.Color.FromArgb(Int32 alpha, Int32 red, Int32 green, Int32 blue)
   at System.Drawing.Color.FromArgb(Int32 red, Int32 green, Int32 blue)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   at ImageManipulation.OctreeQuantizer.Octree.Palletize(Int32 colorCount)
   at ImageManipulation.OctreeQuantizer.GetPalette(ColorPalette original)
   at ImageManipulation.Quantizer.Quantize(Image source)
   at WzComparerR2.Common.BuildInGifEncoder.AppendFrame(Bitmap image, Int32 delay)
   at WzComparerR2.Common.BuildInGifEncoder.AppendFrame(IntPtr pBuffer, Int32 delay)
   at WzComparerR2.PictureBoxEx.<>c__DisplayClass30_4.<SaveAsGif>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

This error occurs when I choose to save image with default encoder in frames with delay value of 30. 
It saves a few images, but not all.

You can find this object/boss through: Base.wz > Map.wz > Obj > BM1.img > boss > spine > 0 > skeleton.atlas

EDIT:

I also get an unexpected error when I choose to save the spine image with default encoder without splitting frames.

**Comment by Kagamia** [comment]
This won't fix, Use Index gif encoder instead.

**Comment by Kagamia** [comment]
ImageManipulation is really an ancient library even <s>I've already given up to fix it</s> I can't find the source code (this is an excuse :D).

https://msdn.microsoft.com/en-us/library/aa479306.aspx

Index gif encoder is more stable and flexable than default encoder.

**Comment by Sunaries** [comment]
I also noticed that Twitter does not support saved GIF images with "Index GIF Encoder" encoder, but it does support "BuildIn". They animate with BuildIn but not with Index GIF Encoder.

**Comment by Sunaries** [comment]
I think Twitter does, yes.

**Comment by Kagamia** [comment]
I've tried but gif all work fine, no bug found :(

Twitter processes it and convert gifs to mp4 videos. I got two videos with the same size.

**Comment by Kagamia** [comment]
duplicated as #75.
